beancount_output: ./beancount_output.beancount
default_currency: usd
healthcheck_url: "https://hc-ping.com/<your-uuid>/beancount"
bsc_endpoint: "https://bsc-mainnet.infura.io/v3/<your-project-id>"
eth_endpoint: "https://mainnet.infura.io/v3/<your-project-id>"

entries:
  - date: 1
    description: Monthly credit cards (bill day 1)
    accounts:
      - account: Liabilities:CreditCard:Example
        currency: CNY
        balance: "-0.00"
  - date: 15
    accounts:
      - account: Assets:Crypto:Wallet
        currency: BTC
        api_function: sources.fetch_wallet_balance
        args:
          address: "0xabc..."
          precision: 8
      - account: Assets:Crypto:BNBWallet
        currency: BNB
        api_function: sources.fetch_bnb_balance_on_bsc
        args:
          address: "0xabc..."
      - account: Assets:Crypto:BNBWallet:USDT
        currency: USDT
        api_function: sources.fetch_usdt_balance_on_bsc
        args:
          address: "0xabc..."
      - account: Assets:Crypto:BNBWallet:USDC
        currency: USDC
        api_function: sources.fetch_usdc_balance_on_bsc
        args:
          address: "0xabc..."
      - account: Assets:Crypto:ETHWallet
        currency: ETH
        api_function: sources.fetch_eth_balance_on_ethereum
        args:
          address: "0xabc..."
      - account: Assets:Crypto:ETHWallet:USDT
        currency: USDT
        api_function: sources.fetch_usdt_balance_on_ethereum
        args:
          address: "0xabc..."
      - account: Assets:Crypto:ETHWallet:USDC
        currency: USDC
        api_function: sources.fetch_usdc_balance_on_ethereum
        args:
          address: "0xabc..."
